### ISSUE TITLE
Error: '' does not exist in current working directory

### ISSUE THREAD

**Issue by wilfredom** [cloudyr/aws.alexa#14]
I generated a Key and Secret, loaded both with `set_secret_key` and `Sys.setenv`, but when I try `url_info(url = "https://www.google.com")`, I get:

`Error: '' does not exist in current working directory ...`

I tried with the CRAN version and the Stable github version.

**Comment by 6884** [comment]
I have the same problem, I see that I get the same error if I enter random values for key and secret... I hope they didn't change the authorization method in the meanwhile :(

**Comment by 6884** [comment]
@wilfredom a person that got it working actually proved that it is not an authorization problem - if you enter wrong credentials, you get a 403 error instead. I am dissecting the url_info function to see where the problem is, somehow it seems I don't get all the functions from the package loaded correctly!

**Comment by 6884** [comment]
Good news @wilfredom - with the help of [this post](https://stackoverflow.com/questions/52623598/r-packge-install-from-github-does-not-exist-in-current-working-directory) I... didn't manage to figure out what was wrong. But I got the `url_info` function working! In brief, did you try downloading the latest version from github? I got it with `githubinstall::githubinstall("aws.alexa")` and now all problems are gone. Weird but effective.

**Comment by soodoku** [comment]
Hey @6884: from your comments, it iseems github v. works and CRAN doesn't. so I have released a new version with changes since the last release, including v4 of signature, to CRAN. It will take a day or two but should fix it. Ping me if it doesn't.

**Comment by wilfredom** [comment]
Hey, thanks @6884 and @soodoku — the use case is long gone, but good to know that this should work now.
