### ISSUE TITLE
traffic history date conversion error

### ISSUE THREAD

**Issue by Btibert3** [cloudyr/aws.alexa#4]
After a handful of successful calls, I ran the example call included in the docs for `traffic_history`.  Below is the error that gets thrown.

```
> traffic_history(url="http://www.google.com", start="20160505")
Error in as.Date.default(date, "%Y%m%d") : 
  do not know how to convert 'date' to class “Date”
```

and my session info

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aws.alexa_0.1.2

loaded via a namespace (and not attached):
 [1] httr_1.2.0          plyr_1.8.4          R6_2.1.2            tools_3.2.3         base64enc_0.1-3    
 [6] withr_1.0.1         curl_0.9.7          Rcpp_0.12.5         aws.signature_0.2.2 memoise_1.0.0      
[11] knitr_1.13          git2r_0.12.1        digest_0.6.9        devtools_1.10.0     XML_3.98-1.4   
```

**Comment by soodoku** [comment]
Thanks. I see the issue. Will issue a patch soon.

**Comment by soodoku** [comment]
Apologies for the bug. It has been patched.

 head(  traffic_history(url="http://www.google.com", start="20160505"))
Request ID:  8ec31bcc-1c8b-ce53-28e6-b72dc30ae889 
Response Status:  Success 
        date page_views_per_million page_views_per_user rank reach_per_million
1 2016-05-25                 116400               18.01    1            438200
2 2016-05-26                 114210               17.77    1            432500
3 2016-05-27                 118260               18.96    1            419900
4 2016-05-28                  77870               12.65    2            386900
5 2016-05-29                  74610               12.26    2            388700
6 2016-05-30                 103640               16.56    1            418700

**Comment by Btibert3** [comment]
Great, thanks for the quick turnaround.  What does it mean when I get the following error:

```
Warning message:
In (function (..., deparse.level = 1)  :
  number of columns of result is not a multiple of vector length (arg 3)
```

The Google example ran as expected, and this could be for a lower-volume site, but not what I was expecting.

**Comment by soodoku** [comment]
Oy. I am coercing the output to a data.frame and this is a coercion warning as the number of cols. in each list item is variable. Do you want to send me a specific example? I can expand the handling to account for this.

**Comment by Btibert3** [comment]
Thanks again.  The first example below throws the error, the second runs fine.

```
traffic_history(url="http://www.collegeweeklive.com", range = 31, start = "20160501")
traffic_history(url="http://www.cappex.com", start="20160505")
```

**Comment by soodoku** [comment]
Great. Apologies again for the bugs. Will have a patch soon.

**Comment by soodoku** [comment]
Hi --- just issued a patch. 

head(traffic_history(url="http://www.collegeweeklive.com", range = 31, start = "20160501"))
Request ID:  ed1d12fa-df22-dd93-f0c0-60f7da87cf20 
Response Status:  Success 
        date page_views_per_million page_views_per_user    rank reach_per_million
1 2016-05-25                   0.21                 3.0  167651                 5
2 2016-05-26                   0.16                 2.2  145029                 5
3 2016-05-27                      0                <NA> 1678987                 0
4 2016-05-28                   0.10                 1.3  201575                 5
5 2016-05-29                   0.16                 1.8  176164                 6
6 2016-05-30                   0.18                 1.8  146578                 7

**Comment by Btibert3** [comment]
perfect, thanks!
