### ISSUE TITLE
start date argument dosen't work.

### ISSUE THREAD

**Issue by statkclee** [cloudyr/aws.alexa#6]
I tried to collect the traffic history with a slightly different setting: start = "20160505".

That's not what I want. I think there there are some bugs in the 'traffic_history' function. 

`> traffic_history(url = "http://www.google.com", start = "20160505")`

Request ID:  d5e2aa-563a-d344-3ae0-7b2fb704c 
Response Status:  Success 
         date page_views_per_million page_views_per_user rank reach_per_million
1  2017-07-01                  66150                6.46    2            407800
2  2017-07-02                  63520                6.36    2            403500
3  2017-07-03                  80300                8.16    1            436900
4  2017-07-04                  77480                7.73    1            435300
5  2017-07-05                  83700                8.50    1            435200
6  2017-07-06                  84000                8.56    1            435200
7  2017-07-07                  81490                8.18    1            428700
8  2017-07-08                  65680                6.50    2            401400
9  2017-07-09                  63920                6.44    2            401300
10 2017-07-10                  87520                9.29    1            437000
11 2017-07-11                  82760                8.64    1            433600
12 2017-07-12                  84280                8.61    1            428100
13 2017-07-13                  84410                8.54    1            427200
14 2017-07-14                  81130                8.15    1            419000
15 2017-07-15                  66680                6.52    2            390600
16 2017-07-16                  64980                6.51    2            389500
17 2017-07-17                  85130                8.76    1            428000
18 2017-07-18                  85730                8.80    1            428300
19 2017-07-19                  85000                8.68    1            427100
20 2017-07-20                  84540                8.59    1            425900
21 2017-07-21                  82140                8.21    1            420000
22 2017-07-22                  66540                6.48    2            391300
23 2017-07-23                  65030                6.49    2            391200
24 2017-07-24                  85070                8.74    1            430000
25 2017-07-25                  85580                8.79    1            427800
26 2017-07-26                  89440                9.42    1            425900
27 2017-07-27                  88730                9.29    1            424200
28 2017-07-28                  86410                8.90    1            414100
29 2017-07-29                  72180                7.28    2            389000
30 2017-07-30                  70500                7.23    2            390300
31 2017-07-31                  89940                9.55    1            426100

**Comment by soodoku** [comment]
Oy. I will investigate and get back.

**Comment by soodoku** [comment]
Apologies for the delay. It was a bug! Not the right case for the argument. Used to work. But Amz became case sensitive for the arguments.

```
traffic_history(url = "http://www.google.com", start = "20160505")
```

```
Request ID:  33348e0a-3528-0c31-4663-467121599592 
Response Status:  Success 
         date page_views_per_million page_views_per_user rank reach_per_million
1  2016-05-05                 107100               17.35    1            417200
2  2016-05-06                 105300               16.67    1            418400
3  2016-05-07                  78210               12.66    2            390400
4  2016-05-08                  75210               12.20    2            388200
5  2016-05-09                 114400               18.33    1            427900
6  2016-05-10                 113800               18.22    1            429600
7  2016-05-11                 113300               17.87    1            429600
8  2016-05-12                 112600               17.69    1            429000
9  2016-05-13                 107100               16.89    1            419300
10 2016-05-14                  77940               12.75    2            388200
11 2016-05-15                  76140               12.57    2            392300
12 2016-05-16                 111800               18.19    1            422600
13 2016-05-17                 115400               18.36    1            427900
14 2016-05-18                 114100               18.06    1            425800
15 2016-05-19                 113600               17.66    1            430300
16 2016-05-20                 110100               16.88    1            426000
17 2016-05-21                  80630               12.65    2            397200
18 2016-05-22                  78220               12.51    2            398700
19 2016-05-23                 116900               18.32    1            435200
20 2016-05-24                 116700               18.28    1            434900
21 2016-05-25                 116400               18.01    1            438200
22 2016-05-26                 114200               17.77    1            432500
23 2016-05-27                 118300               18.96    1            419900
24 2016-05-28                  77870               12.65    2            386900
25 2016-05-29                  74610               12.26    2            388700
26 2016-05-30                 103600               16.56    1            418700
27 2016-05-31                 121300               19.19    1            427700
28 2016-06-01                 120100               18.81    1            439300
29 2016-06-02                 117300               18.41    1            431200
30 2016-06-03                 112500               17.58    1            429400
31 2016-06-04                  83120               13.26    2            404200
```
