### ISSUE TITLE
403 authentication failure

### ISSUE THREAD

**Issue by diplodata** [cloudyr/aws.alexa#8]
Trying to get CRAN version 0.1.4 working, and getting 403 responses. I'm signed up to _alexa.com_ (trial), have created a key in the AWS IAM console, and have apparently authenticated with:

    set_secret_key(key='xxx', secret='yyy')

No response, but no error either.  But:

```
> url_info(url = "google.com")
Error: HTTP failure: 403
```

I have no idea where to go from here.  Any ideas?

**Comment by diplodata** [comment]
So I'm still getting 403. I'm on aws.alexa 0.1.5, running on R 3.4.3 on Mac Higher Sierra (10.13.3).  I just refreshed my access key and instead get a 401 error now.

Could this be a AWS region-specific thing?

I'm unclear how AWS is supposed to make the link between my alexa.com trial and my AWS account. I'm using the same email to access both, but I've seen no indication that AWS has made this connection. And there's no API info in alexa.com to refer to.

I'm happy to share my AWS key details privately if it would help to make this reproducible.

**Comment by soodoku** [comment]
Hey man,

I tried at my end and things work normally. 

But my sense is that you are doing something basic incorrectly to get a 403 error. Do look carefully through the readme and then the amazon website (not the most user friendly). Sometimes it is as simple as getting the key and secret mixed up. Key is generally shorter than secret. 

You can reach out to me via email provided in the package description:
https://github.com/cloudyr/aws.alexa/blob/master/DESCRIPTION
